# --- Active Pywal Colors ---
# This pulls in the file Pywal generates from your template
include=~/.cache/wal/colors-fuzzel.ini

# --- Layout & Behavior ---
font=Monaspace Neon:size=14
line-height=30
fields=name,generic,comment,categories,filename,keywords
terminal=foot -e
prompt="> "
layer=overlay
lines=12
width=40

[border]
radius=6
width=2
