# --- Pywal Colors ---
include ~/.cache/wal/colors-kitty.conf

# --- Layout & Styling ---
background #000000
background_opacity 0.7
font_size 13.0

# --- Fonts ---
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic

# --- Cursor Trail ---
cursor_trail 1
cursor_trail_decay 0.1 0.35
cursor_trail_start_threshold 2
