wallpaper {
		monitor = DP-3
		path = /home/B0LD/Pictures/Wallpapers/girl_fighting_dome_gray.png
		fit_mode = contain
}

wallpaper {
		monitor = DP-4
		path = /home/B0LD/Pictures/Wallpapers/girl_fighting_dome_gray_UW.png
		fit_mode = cover
}
